databases:
  - name: mastodon-db
    databaseName: mastodon
    ipAllowList: []
    postgresMajorVersion: 14
services:
  - type: redis
    name: mastodon-redis
    ipAllowList: []
  - type: web
    name: mastodon-web
    env: docker
    repo: https://github.com/kyleconroy/mastodon-render.git
    branch: main
    envVars:
      - key: SINGLE_USER_MODE
        value: true
      - key: DB_HOST
        fromDatabase:
          name: mastodon-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: mastodon-db
          property: user
      - key: DB_PORT
        fromDatabase:
          name: mastodon-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: mastodon-db
          property: database
      - key: DB_PASS
        fromDatabase:
          name: mastodon-db
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: mastodon-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: mastodon-redis
          property: port
      - key: LOCAL_DOMAIN
        sync: false
      # Make sure to use `rake secret` to generate secrets
      - key: OTP_SECRET
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      # Generate with `rake mastodon:webpush:generate_vapid_key`
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
